server:
  port: 7000

#服务的名称
spring:
  application:
    name: micro-service-cloud-client

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:6003/eureka
  instance:
    instance-id: micro-service-cloud-client
    prefer-ip-address: true

info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples