server:
  port: 8001
spring:
  application:
    name: eureka-server-8001
eureka:
  instance:
    hostname: eureka-server-8001
  client:
    # 从其他实例同步服务注册信息
    fetch-registry: true
    #向其他的eureka注册当前eureka实例
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://eureka-server-8002:8002/eureka/ #注册到另一个Eureka注册中心



